### ISSUE TITLE
An issue with icons

### ISSUE THREAD

**Issue by bshumylo** [dgrammatiko/muta#106]
Hi
There is an issue with icons after making MUTA style default

![Screenshot 2023-06-28 at 11 13 48](https://github.com/dgrammatiko/muta/assets/94482775/cebc8b57-0054-4408-9c34-904017c820d4)

**Comment by dgrammatiko** [comment]
What browser are you using?

**Comment by bshumylo** [comment]
Brave

**Comment by dgrammatiko** [comment]
Should be fixed with version 4.1.1.

If you still experience problems, please reopen this issue.

Thanks for reporting!
