### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by bshumylo** [dgrammatiko/muta#113]
Hi
Is there a possibility to customize a favicon for an Admin Panel?
If no, can you add it?

Regards.

**Comment by dgrammatiko** [comment]
I’m not sure what you mean with the `customize a favicon for an Admin Panel` but if you mean use your own Favicon then this is already possible:
https://github.com/dgrammatiko/muta/blob/56c7c3263c033df47a9de36a7266c765d26d0e14/src/templates/administrator/muta/html/layouts/muta/partials/favicons.php#L16

just add a favicon.png in the media/templates/muta/images and presto 👌

**Comment by bshumylo** [comment]
Great! Thank you. That is exactly what I need. 

And will it stay after Muta template or Joomla updates?

**Comment by dgrammatiko** [comment]
Any updates will not affect your favicon 😉

**Comment by bshumylo** [comment]
Good news, thank you 🙂
