### ISSUE TITLE
deprecated error

### ISSUE THREAD

**Issue by gwstyles** [dgrammatiko/muta#118]
Good day, just tried your template and I have:-
Deprecated
: Creation of dynamic property Joomla\CMS\WebAsset\WebAssetManager::$version is deprecated in
/home/wildherbsco/public_html/administrator/templates/muta/src/Helper/ParamsEvaluatorHelper.php
on line
121
J 4.3.4 php 8.2

**Comment by dgrammatiko** [comment]
2.1.3 should fix it. I forgot to remove one line, duh...


Thanks for reporting
