### ISSUE TITLE
Joomla! Statistics

### ISSUE THREAD

**Issue by Quy** [dgrammatiko/muta#121]
![muta-stats](https://github.com/dgrammatiko/muta/assets/368084/cddecb32-c0d2-45ba-8d8c-a3f3d4ba3f88)

**Comment by dgrammatiko** [comment]
This is on 5.0.0-beta3?

**Comment by Quy** [comment]
Yes

**Comment by dgrammatiko** [comment]
Won't fix, reason: this alert is only visible once after the installation of Joomla. Most people will get rid of it before even installing this template. Also it doesn't worth my time ;)

Thanks for reporting
