### ISSUE TITLE
No dark/light switch in Joomla5

### ISSUE THREAD

**Issue by renekreijveld** [dgrammatiko/muta#128]
After installation of the Muta template in Joomla 5 I set the Muta Administrator template as the default style. However, there is no option to switch between dark and light. Am I missing something?

**Comment by dgrammatiko** [comment]
![IMG_0474](https://github.com/dgrammatiko/muta/assets/3889375/d2076e1d-44cb-4be1-96f6-a0aa34b04aaf)

**Comment by renekreijveld** [comment]
That solved it Dimitris. Thanks!
