### ISSUE TITLE
Huge admin login form

### ISSUE THREAD

**Issue by red1967** [dgrammatiko/muta#134]
Hi, I have 2 websites using the muta admin template. Both have been upgraded from Joomla 3.

On this website the login is normal size:
https://musingsinparticular.com/administrator/

On this website the login form is huge:
https://certatek.com/beta/administrator/index.php

I raised the issue in the joomla forum:
https://forum.joomla.org/viewtopic.php?f=834&t=1007917

They say the template needs to have this code in it:
.plg_system_webauthn_login_button svg {
	width: 30px;
	margin: 4px;
}

Instead of:
.plg_system_webauthn_login_button svg {
	-webkit-margin-end: 2px;
	margin-inline-end: 2px;
}

It's bugging me. I do not understand why I get different behaviour for the same template on different websites!

**Comment by red1967** [comment]
I figured it out. It's the title length of the website that stretches the login form wider when using the muta template.

**Comment by dgrammatiko** [comment]
Fixed in version 2.2.0.

Thanks
