### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by bshumylo** [dgrammatiko/muta#95]
Hi
Thank you for a template.
I translated it to Ukrainian language – please add it.
[Archive on Google Drive.](https://drive.google.com/file/d/187Ai6cyt0rp8cR2vq6KY1N1SlUKaIZlN/view?usp=sharing)

**Comment by dgrammatiko** [comment]
I added the language file here https://github.com/dgrammatiko/muta/pull/96

Will do a release the weekend.

Thanks for your contribution.
